import type { FeedItem } from "./types"

export const liveUpdatePool: FeedItem[] = [
  {
    kind: "news",
    id: "live-news-01",
    category: "technology",
    source: "Reuters",
    headline: "Cloud providers report record demand for AI inference capacity",
    summary: "Data center operators say inference workloads have overtaken training as the primary driver of new capacity orders.",
    imageUrl: "https://picsum.photos/seed/live-tech-01/640/400",
    publishedAt: new Date().toISOString(),
    url: "https://reuters.com",
  },
  {
    kind: "news",
    id: "live-news-02",
    category: "sports",
    source: "ESPN",
    headline: "Late free throws seal a tight finish in tonight's game",
    summary: "A back-and-forth fourth quarter came down to the final possession, with the home crowd on its feet for the last two minutes.",
    imageUrl: "https://picsum.photos/seed/live-sports-01/640/400",
    publishedAt: new Date().toISOString(),
    url: "https://espn.com",
  },
  {
    kind: "news",
    id: "live-news-03",
    category: "finance",
    source: "Bloomberg",
    headline: "Futures tick higher ahead of tomorrow's inflation print",
    summary: "Traders are positioning cautiously overnight, with most of the week's volume expected once the data lands.",
    imageUrl: "https://picsum.photos/seed/live-finance-01/640/400",
    publishedAt: new Date().toISOString(),
    url: "https://bloomberg.com",
  },
  {
    kind: "social",
    id: "live-social-01",
    handle: "@newsroomlive",
    displayName: "Newsroom Live",
    avatarUrl: "https://i.pravatar.cc/150?img=5",
    body: "Following this one closely, updates as they land.",
    postedAt: new Date().toISOString(),
    likeCount: 12,
    repostCount: 3,
    hashtags: ["breaking"],
  },
  {
    kind: "social",
    id: "live-social-02",
    handle: "@fieldreport",
    displayName: "Field Report",
    avatarUrl: "https://i.pravatar.cc/150?img=9",
    body: "Crowd reaction here has been something else tonight.",
    postedAt: new Date().toISOString(),
    likeCount: 34,
    repostCount: 8,
    hashtags: ["live"],
  },
]
