import type { MovieRecommendation } from "./types"

export const movieRecommendations: MovieRecommendation[] = [
  {
    kind: "movie",
    id: "movie-01",
    title: "Toy Story 5",
    tagline: "Some toys never go out of style",
    posterUrl: "https://image.tmdb.org/t/p/w500/rki5qLuwb0xnnE9seehxO9TlLhW.jpg",
    releaseYear: 2026,
    rating: 8.1,
    genres: ["Animation", "Family", "Comedy"],
  },
  {
    kind: "movie",
    id: "movie-02",
    title: "The Super Mario Galaxy Movie",
    tagline: "The Mushroom Kingdom expands",
    posterUrl: "https://picsum.photos/seed/movie-mariogalaxy/400/600",
    releaseYear: 2026,
    rating: 7.4,
    genres: ["Animation", "Adventure", "Family"],
  },
  {
    kind: "movie",
    id: "movie-03",
    title: "Project Hail Mary",
    tagline: "One scientist, one ship, one shot at saving Earth",
    posterUrl: "https://picsum.photos/seed/movie-hailmary/400/600",
    releaseYear: 2026,
    rating: 8.4,
    genres: ["Science Fiction", "Adventure"],
  },
  {
    kind: "movie",
    id: "movie-04",
    title: "The Devil Wears Prada 2",
    tagline: "Fashion never forgets",
    posterUrl: "https://picsum.photos/seed/movie-prada2/400/600",
    releaseYear: 2026,
    rating: 7.2,
    genres: ["Comedy", "Drama"],
  },
  {
    kind: "movie",
    id: "movie-05",
    title: "Scream 7",
    tagline: "The killer always comes home",
    posterUrl: "https://picsum.photos/seed/movie-scream7/400/600",
    releaseYear: 2026,
    rating: 6.8,
    genres: ["Horror", "Mystery"],
  },
  {
    kind: "movie",
    id: "movie-06",
    title: "Michael",
    tagline: "The world's biggest musical biopic",
    posterUrl: "https://picsum.photos/seed/movie-michael/400/600",
    releaseYear: 2026,
    rating: 7.9,
    genres: ["Biography", "Drama", "Music"],
  },
  {
    kind: "movie",
    id: "movie-07",
    title: "Hoppers",
    tagline: "Small creature, big trouble",
    posterUrl: "https://picsum.photos/seed/movie-hoppers/400/600",
    releaseYear: 2026,
    rating: 7.0,
    genres: ["Animation", "Comedy"],
  },
  {
    kind: "movie",
    id: "movie-08",
    title: "Star Wars: The Mandalorian and Grogu",
    tagline: "This is the way, together",
    posterUrl: "https://picsum.photos/seed/movie-mandalorian/400/600",
    releaseYear: 2026,
    rating: 8.0,
    genres: ["Science Fiction", "Action", "Adventure"],
  },
]
