import type { SocialPost } from "./types"

export const socialPosts: SocialPost[] = [
  {
    kind: "social",
    id: "social-01",
    handle: "@chipwatcher",
    displayName: "Priya Nair",
    avatarUrl: "https://i.pravatar.cc/150?img=32",
    body: "Every earnings call this quarter has the same three words in it: inference, orchestration, energy. That's the whole AI economy right now.",
    postedAt: "2026-08-14T14:20:00Z",
    likeCount: 842,
    repostCount: 121,
    hashtags: ["ai", "markets"],
  },
  {
    kind: "social",
    id: "social-02",
    handle: "@courtsidecarl",
    displayName: "Carl Whitfield",
    avatarUrl: "https://i.pravatar.cc/150?img=15",
    body: "Watching a Hall of Famer's number go up in the rafters tonight hits different when you remember watching him play as a kid.",
    postedAt: "2026-08-14T23:05:00Z",
    likeCount: 1560,
    repostCount: 233,
    hashtags: ["nba", "hoops"],
  },
  {
    kind: "social",
    id: "social-03",
    handle: "@popcornpanel",
    displayName: "Devika Rao",
    avatarUrl: "https://i.pravatar.cc/150?img=47",
    body: "Just walked out of the new Mario movie. Didn't expect to tear up during a Bowser scene but here we are.",
    postedAt: "2026-08-13T20:40:00Z",
    likeCount: 2093,
    repostCount: 310,
    hashtags: ["movies", "mario"],
  },
  {
    kind: "social",
    id: "social-04",
    handle: "@ratesandrisk",
    displayName: "Malik Oduya",
    avatarUrl: "https://i.pravatar.cc/150?img=8",
    body: "Thirty year yield at levels we haven't seen in 25 years and half my timeline is still arguing about whether rate cuts are coming. Read the bond market, not the headlines.",
    postedAt: "2026-08-14T19:10:00Z",
    likeCount: 674,
    repostCount: 98,
    hashtags: ["bonds", "fed"],
  },
  {
    kind: "social",
    id: "social-05",
    handle: "@fieldnotesfrmnina",
    displayName: "Nina Escobar",
    avatarUrl: "https://i.pravatar.cc/150?img=21",
    body: "Robotaxis hitting European streets in the thousands, not dozens, is the actual story. Pilots are easy. Fleets are the test.",
    postedAt: "2026-08-14T08:55:00Z",
    likeCount: 455,
    repostCount: 64,
    hashtags: ["autonomy", "mobility"],
  },
  {
    kind: "social",
    id: "social-06",
    handle: "@lineupleo",
    displayName: "Leo Marchetti",
    avatarUrl: "https://i.pravatar.cc/150?img=59",
    body: "Bullpen blew another lead in the eighth. At some point it stops being bad luck and starts being a pattern.",
    postedAt: "2026-08-14T22:30:00Z",
    likeCount: 389,
    repostCount: 52,
    hashtags: ["mlb", "baseball"],
  },
  {
    kind: "social",
    id: "social-07",
    handle: "@codeandcoffee",
    displayName: "Ananya Bhatt",
    avatarUrl: "https://i.pravatar.cc/150?img=44",
    body: "Autonomous coding agents shipping straight to prod by default is going to make code review a completely different job in two years.",
    postedAt: "2026-08-14T06:45:00Z",
    likeCount: 1203,
    repostCount: 210,
    hashtags: ["devtools", "ai"],
  },
  {
    kind: "social",
    id: "social-08",
    handle: "@sundaymatinee",
    displayName: "Owen Faulkner",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    body: "Scream 7 trailer just dropped and my group chat has not stopped buzzing for an hour.",
    postedAt: "2026-08-12T17:15:00Z",
    likeCount: 980,
    repostCount: 145,
    hashtags: ["horror", "movies"],
  },
]
